const fs = require('fs');
let content = fs.readFileSync('app/timesheet/webapp/view/App.view.xml', 'utf8');

const replacements = {
  'text="My Timesheet"': 'text="{i18n>appTitle}"',
  'text="Loading..."': 'text="{i18n>txtLoading}"',
  'text="Dashboard"': 'text="{i18n>navDashboard}"',
  'text="My Attendance"': 'text="{i18n>navAttendance}"',
  'text="Work Calendar"': 'text="{i18n>navCalendar}"',
  'text="My Requests"': 'text="{i18n>navRequests}"',
  'text="My History"': 'text="{i18n>navHistory}"',
  'text="My Reports"': 'text="{i18n>navReports}"',
  'headerText="Dashboard"': 'headerText="{i18n>navDashboard}"',
  'text="Dashboard content will be developed later."': 'text="{i18n>txtDashboardComing}"',
  'headerText="My Attendance"': 'headerText="{i18n>navAttendance}"',
  'text="Search"': 'text="{i18n>btnSearch}"',
  'text="Export"': 'text="{i18n>btnExport}"',
  'text="No."': 'text="{i18n>colNo}"',
  'text="Date"': 'text="{i18n>colDate}"',
  'text="Checkin"': 'text="{i18n>colCheckin}"',
  'text="Checkout"': 'text="{i18n>colCheckout}"',
  'text="Status (In/Out)"': 'text="{i18n>colStatusInOut}"',
  'text="Actual Working"': 'text="{i18n>colActualWorking}"',
  'text="Overtime (Hours)"': 'text="{i18n>colOvertimeHours}"',
  'text="Credit Leave (day)"': 'text="{i18n>colCreditLeaveDay}"',
  'text="Unpaid Leave (day)"': 'text="{i18n>colUnpaidLeaveDay}"',
  'text="Request (Accept/Sent)"': 'text="{i18n>colRequestAcceptSent}"',
  'text="Create request"': 'text="{i18n>btnCreateRequest}"',
  'headerText="Work Calendar"': 'headerText="{i18n>navCalendar}"',
  'text="Full Attendance"': 'text="{i18n>statusFullAttendance}"',
  'text="Late / Leave Early"': 'text="{i18n>statusLateLeaveEarly}"',
  'text="Absent"': 'text="{i18n>statusAbsent}"',
  'text="Scheduled"': 'text="{i18n>statusScheduled}"',
  'text="Off / No Schedule"': 'text="{i18n>statusOffNoSchedule}"',
  'headerText="Attendance Details"': 'headerText="{i18n>detPanelTitle}"',
  'text="Scheduled Hours"': 'text="{i18n>detSchHours}"',
  'text="Shift"': 'text="{i18n>detShift}"',
  'text="Start Time"': 'text="{i18n>detStart}"',
  'text="End Time"': 'text="{i18n>detEnd}"',
  'text="Actual Hours"': 'text="{i18n>detActHours}"',
  'text="Clock In"': 'text="{i18n>detClockIn}"',
  'text="Clock Out"': 'text="{i18n>detClockOut}"',
  'text="Status"': 'text="{i18n>detStatus}"',
  'text="Select a date on the calendar to view details."': 'text="{i18n>detPlaceholder}"',
  'headerText="My Requests"': 'headerText="{i18n>navRequests}"',
  'text="Team Approvals"': 'text="{i18n>reqViewTeamAppr}"',
  'text="Refresh"': 'text="{i18n>btnRefresh}"',
  'text="All"': 'text="{i18n>statusAll}"',
  'text="Pending"': 'text="{i18n>statusPending}"',
  'text="Approved"': 'text="{i18n>statusApproved}"',
  'text="Rejected"': 'text="{i18n>statusRejected}"',
  'noDataText="No requests found."': 'noDataText="{i18n>txtNoDataReq}"',
  'text="Type"': 'text="{i18n>colType}"',
  'text="Date Range"': 'text="{i18n>colDateRange}"',
  'text="Duration"': 'text="{i18n>colDuration}"',
  'text="Approver"': 'text="{i18n>colApprover}"',
  'text="Reason"': 'text="{i18n>colReason}"',
  'text="Created"': 'text="{i18n>colCreated}"',
  'text="Actions"': 'text="{i18n>colActions}"',
  'text="Cancel"': 'text="{i18n>btnCancel}"',
  'text="Approve"': 'text="{i18n>btnApprove}"',
  'text="Reject"': 'text="{i18n>btnReject}"',
  'headerText="My History"': 'headerText="{i18n>navHistory}"',
  'noDataText="No history records found."': 'noDataText="{i18n>txtNoDataHist}"',
  'text="SAP Status"': 'text="{i18n>colSapStatus}"',
  'headerText="My Reports"': 'headerText="{i18n>navReports}"',
  'text="Coming soon"': 'text="{i18n>txtReportsComing}"',
  'title="Create Request"': 'title="{i18n>dialogTitleCreateReq}"',
  'text="Day Off"': 'text="{i18n>reqTypeDayOff}"',
  'text="Edit Timesheet"': 'text="{i18n>reqTypeEdit}"',
  'text="Overtime"': 'text="{i18n>reqTypeOvertime}"',
  'text="Evidence"': 'text="{i18n>lblEvidence}"',
  'text="Corrected Start Time"': 'text="{i18n>lblCorrectedStart}"',
  'text="Corrected End Time"': 'text="{i18n>lblCorrectedEnd}"',
  'text="Overtime Start Time"': 'text="{i18n>lblOvertimeStart}"',
  'text="Overtime End Time"': 'text="{i18n>lblOvertimeEnd}"',
  'text="Send Request"': 'text="{i18n>btnSendRequest}"',
  'text="Close"': 'text="{i18n>btnClose}"',
  'text="January"': 'text="{i18n>mJan}"',
  'text="February"': 'text="{i18n>mFeb}"',
  'text="March"': 'text="{i18n>mMar}"',
  'text="April"': 'text="{i18n>mApr}"',
  'text="May"': 'text="{i18n>mMay}"',
  'text="June"': 'text="{i18n>mJun}"',
  'text="July"': 'text="{i18n>mJul}"',
  'text="August"': 'text="{i18n>mAug}"',
  'text="September"': 'text="{i18n>mSep}"',
  'text="October"': 'text="{i18n>mOct}"',
  'text="November"': 'text="{i18n>mNov}"',
  'text="December"': 'text="{i18n>mDec}"'
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.split(key).join(value);
}

fs.writeFileSync('app/timesheet/webapp/view/App.view.xml', content);
console.log('App.view.xml successfully updated using script.');
